# Generated by Django 5.1.1 on 2024-10-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0003_alter_entry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diaryapp.signindetail'),
        ),
    ]
