# Generated by Django 4.2.16 on 2024-09-18 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_comment_commentauthor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='attachment',
            field=models.FileField(blank=True, upload_to='static/attachments/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
